name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  python-tests:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'        
    - name: Install Python packages
      run: |
        pip install -r requirements.txt
        python setup.py develop
    - name: Run dual momentum Tests
      run: |
        cd dual_momentum/tests 
        python -m unittest 
      
